/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#241a0c",
        "primary-fixed": "#ffdcc3",
        "tertiary-fixed": "#ffdbcd",
        "surface-container-high": "#ebe8e3",
        "tertiary-container": "#b05e38",
        "primary-fixed-dim": "#ffb77d",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#554336",
        "outline": "#887364",
        "secondary-fixed-dim": "#d7c3ae",
        "surface": "#fcf9f4",
        "surface-container": "#f0ede8",
        "on-tertiary-fixed-variant": "#76320f",
        "on-tertiary-fixed": "#360f00",
        "surface-dim": "#dcdad5",
        "on-secondary-fixed-variant": "#524534",
        "on-primary-container": "#fffbff",
        "on-background": "#1c1c19",
        "tertiary": "#914723",
        "secondary-fixed": "#f4dfc9",
        "primary-container": "#b15f00",
        "primary": "#8d4b00",
        "on-error-container": "#93000a",
        "background": "#fcf9f4",
        "surface-container-highest": "#e5e2dd",
        "secondary": "#6b5c4a",
        "surface-container-low": "#f6f3ee",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1c1c19",
        "surface-variant": "#e5e2dd",
        "tertiary-fixed-dim": "#ffb596",
        "inverse-primary": "#ffb77d",
        "on-primary-fixed-variant": "#6e3900",
        "on-primary": "#ffffff",
        "surface-bright": "#fcf9f4",
        "on-primary-fixed": "#2f1500",
        "outline-variant": "#dbc2b0",
        "inverse-surface": "#31302d",
        "secondary-container": "#f1dcc6",
        "on-secondary-container": "#6f604e",
        "inverse-on-surface": "#f3f0eb",
        "on-tertiary-container": "#fffbff",
        "surface-tint": "#904d00"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        xl: "32px",
        xs: "4px",
        lg: "24px",
        gutter: "20px",
        sm: "8px",
        "margin-page": "40px",
        unit: "4px",
        md: "16px"
      },
      fontFamily: {
        "display-doc": ["Merriweather"],
        "headline-md": ["Public Sans"],
        "label-caps": ["Public Sans"],
        "label-sm": ["Public Sans"],
        "body-ui": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "body-doc": ["Merriweather"]
      },
      fontSize: {
        "display-doc": ["32px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-ui": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-doc": ["16px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
